### ISSUE TITLE
🏆Music

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-51#27]
There is music for the following

- [x] A background music loop #28 
- [ ] The game start #29 (stretch though)
- [ ] the game over condition #30 
- [ ] the win condition #31
